version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 849857290067.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_NAME:$REPO_TAG_PREFIX -f $DOCKERFILE_PATH .
      - docker tag $REPO_NAME:$REPO_TAG_PREFIX 849857290067.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$CODEBUILD_BUILD_NUMBER
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 849857290067.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - printf '[{"name":"%s","imageUri":"849857290067.dkr.ecr.%s.amazonaws.com/%s:%s"}]' "$CONTAINER_NAME" "$AWS_REGION" "$REPO_NAME" "$REPO_TAG_PREFIX"